# Generated by Django 3.1.2 on 2022-02-04 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oop_django', '0002_auto_20220115_1452'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=1000)),
                ('text', models.CharField(max_length=1000)),
            ],
        ),
        migrations.DeleteModel(
            name='Photo',
        ),
    ]
